### ISSUE TITLE
Leak in channels after reconnect was done

### ISSUE THREAD

**Issue by nikolay-parovoy** [vanthoainguyen/Burrow.NET#19]
I found that after message was published to the RabbitMQ queue when I make the close connection from RabbitMQ admin UI and when recconection is done I can see increase in channels by 1 and this channel not used anymore.

I created a small application (https://www.dropbox.com/s/v54ck1ovgdo8dof/BurrowChannelsLeakApp.zip?dl=0) for you to test it, after each message was published make the connection close from RabbutMQ admin UI and you will see those channels. 
![force_close](https://cloud.githubusercontent.com/assets/7254776/6826192/b8899f90-d310-11e4-84c7-759811facf96.png)

**Comment by vanthoainguyen** [comment]
Thank mate, will check this tonight

**Comment by vanthoainguyen** [comment]
Found the problem, I'm fixing unit tests, will commit tomorrow.

**Comment by nikolay-parovoy** [comment]
Good news. Thanx!
