### ISSUE TITLE
Connection exception handling DurableConnection does not call custom IRabbitWatcher.ErrorFormat to log errors

### ISSUE THREAD

**Issue by nikolay-parovoy** [vanthoainguyen/Burrow.NET#21]
I have implemented custom IRabbitWatcher and added it to the tunnel creation:

var watcher = new CustomRabbitWatcher();
var tunnel = RabbitTunnel.Factory.WithPrioritySupport().Create("host=localhost;username=guest;password=guest", watcher).WithPrioritySupport();

and when I make consumer subscription I can see that all info messages are correctly passed to my custom IRabbitWatcher implementation (messages like: INFO  [(null)] - Subscribed to: Burrow.Queue.SampleQueue_Priority1 with subscriptionName: ), but when I stop RabbitMQ service I can see that in console I have messages like this:
"Failed to connect to Broker: 'localhost', VHost: '/'. Retrying in 4000 ms
Check HostName, VirtualHost, Username and Password.
ExceptionMessage: None of the specified endpoints were reachable"

but they are not passed to the my custom instance of IRabbitWatcher to the method ErrorFormat(string format, params object[] args), but in the DurableConnection.cs in the method HandleConnectionException(Exception ex) you have this:

_watcher.ErrorFormat("Failed to connect to Broker: '{0}', VHost: '{1}'. Retrying in {2} ms\n" +
                    "Check HostName, VirtualHost, Username and Password.\n" +
                    "ExceptionMessage: {3}",
                    ConnectionFactory.HostName,
                    ConnectionFactory.VirtualHost,
                    _retryPolicy.DelayTime,
                    ex.Message);

Working with the latest version Burrow.Extras.1.0.30.

**Comment by vanthoainguyen** [comment]
Try set Global.DefaultWatcher to see if it works

Il'll check tomorrow anyway

Thanks

**Comment by nikolay-parovoy** [comment]
I did it too, but it didn't work either.

**Comment by vanthoainguyen** [comment]
Have u try setting the global before creating the tunnel?

**Comment by nikolay-parovoy** [comment]
yes

**Comment by vanthoainguyen** [comment]
I couldn't reproduce it mate. Here is the demo. Check it out.
https://dl.dropboxusercontent.com/u/81698224/2015-04-21/CustomRabbitWatcherDemo.zip

**Comment by vanthoainguyen** [comment]
Actually, you're testing subscribing. Let me test again.

**Comment by vanthoainguyen** [comment]
Still cannot reproduce the problem.

https://dl.dropboxusercontent.com/u/81698224/2015-04-21/CustomRabbitWatcherDemo.zip

**Comment by nikolay-parovoy** [comment]
I cannot reproduce on your demo too. Will check my code again to find what is different in my configurations and your demo.

Thanx!

**Comment by nikolay-parovoy** [comment]
Not an issue. Problem was in other part of code that was used default console logger as watcher. 
So my custom watcher was used after default one was used in durable connection.

Sorry for that.
