### ISSUE TITLE
RabbitMQ Client 3.5.4.0 Issue

### ISSUE THREAD

**Issue by normanhh3** [vanthoainguyen/Burrow.NET#22]
Hello,

When attempting to create a connection I am getting an exception attempting to load a type "ConnectionShutdownEventHandler" and at this point am assuming that Burrow version 1.0.29.0 is incompatible with RabbitMQ.Client 3.5.4.0 due to a change in the RabbitMQ client.

Thoughts?

**Comment by normanhh3** [comment]
I ended up just installing the 3.4.0.0 version of the RabbitMQ client and all is well again.

**Comment by vanthoainguyen** [comment]
Latest version: 1.0.30

**Comment by normanhh3** [comment]
Hello, just ran into an issue trying to upgrade to the latest RabbitMQ.Client.  Had the same issue, but this time I really DO need to upgrade the RabbitMQ client.  When my package pulls in the Burrow.NET dll for the 1.0.30 package, the DLL that I get in the lib directory has version 1.0.29 in it.  Furthermore, with JustDecompile I found references to the offending RabbitMQ.Client types that are missing from the latest version.

Any chance you might be willing to double-check the NuGet package and let me know if I'm crazy or not?

Thanks!

**Comment by vanthoainguyen** [comment]
Will check it soon mate

**Comment by vanthoainguyen** [comment]
pushed new version to nuget, it will require RabbitMQ.Client 3.5.6
Let me know if there is any issue

**Comment by normanhh3** [comment]
Looks like 3.5.6 is working just fine now with it. :-)  Thanks!
